/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };